// apps/dev/nextjs/components/footer.tsx
import Link from "next/link"
import styles from "./footer.module.css"
import packageJSON from "nextauth.js/package.json"

export default function Footer() {
  return (
    <footer className={styles.footer}>
      <ul className={styles.navItems}>
        <div className={styles.navItemsLeft}>
          <li className={styles.navItem}>
            <a href="https://auth.khulnasoft.com">Documentation</a>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path>
              <polyline points="15 3 21 3 21 9"></polyline>
              <line x1="10" x2="21" y1="14" y2="3"></line>
            </svg>
          </li>
          <li className={styles.navItem}>
            <a href="https://www.npmjs.com/package/next-auth">NPM</a>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path>
              <polyline points="15 3 21 3 21 9"></polyline>
              <line x1="10" x2="21" y1="14" y2="3"></line>
            </svg>
          </li>
          <li className={styles.navItem}>
            <a href="https://github.com/khulnasoft/nextdev-example">GitHub</a>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path>
              <polyline points="15 3 21 3 21 9"></polyline>
              <line x1="10" x2="21" y1="14" y2="3"></line>
            </svg>
          </li>
          <li className={styles.navItem}>
            <Link href="/policy">Policy</Link>
          </li>
        </div>
        <li className={styles.navItem} style={{ margin: "0" }}>
          <img
            className={styles.footerLogo}
            src="https://auth.khulnasoft.com/img/logo-sm.png"
            alt="NextAuth.js Logo"
          />
          <Link href="https://npmjs.org/package/next-auth">
            {packageJSON.version}
          </Link>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path>
            <polyline points="15 3 21 3 21 9"></polyline>
            <line x1="10" x2="21" y1="14" y2="3"></line>
          </svg>
        </li>
      </ul>
    </footer>
  )
}

// apps/examples/sveltekit/src/components/footer.svelte
<script lang="ts">
  import packageJSON from "@nextauth.js/sveltekit/package.json"
  import ExternalIcon from "./external-icon.svelte"
</script>

<footer>
  <div>
    <a href="https://sveltekit.auth.khulnasoft.com"
      >Documentation <ExternalIcon /></a
    >
    <a href="https://www.npmjs.com/package/next-auth"> NPM <ExternalIcon /> </a>
    <a
      href="https://github.com/khulnasoft/nextdev/tree/main/apps/examples/sveltekit"
    >
      Source on GitHub <ExternalIcon />
    </a>
    <a class="no-underline" href="/policy">Policy</a>
  </div>
  <div>
    <img src="https://auth.khulnasoft.com/img/logo-sm.png" alt="NextAuth.js Logo" />
    <a href="https://www.npmjs.com/package/@nextauth.js/sveltekit">
      @nextauth.js/sveltekit@{packageJSON.version}
      <ExternalIcon />
    </a>
  </div>
</footer>

<style>
  footer {
    display: flex;
    width: 100%;
    justify-content: space-between;
    align-items: center;
    padding-inline: 1.25rem;
    margin-block: 2rem;
  }
  footer > div {
    gap: 1rem;
    display: flex;
    flex-wrap: wrap;
    align-items: center;
  }
  footer a {
    color: #333;
    text-underline-offset: 4px;
    font-weight: 500;
    display: flex;
    align-items: flex-end;
    gap: 0.25rem;
  }
  footer img {
    width: 24px;
    height: 24px;
  }
  .no-underline {
    text-decoration: none;
  }
</style>
